export { findFocusedDecorationAnchor, rangeToHunkIndex } from "./decorations.ts";
export {
	type HighlightedLines,
	prepareQuotedSyntaxHighlighting,
	prepareSyntaxHighlighting,
	type QuotedCode,
	quotedLineSpans,
	type SyntaxBackend,
	type SyntaxHighlightingPreparation,
	type SyntaxHighlightWarning,
} from "./highlight.ts";
export type { DiffChromeWidths } from "./layout.ts";
export {
	type MermaidDirection,
	type MermaidEdge,
	type MermaidFlowchart,
	type MermaidNode,
	parseMermaidFlowchart,
} from "./mermaid.ts";
export { drawMermaid } from "./mermaidAscii.ts";
export { countDiffStats, createDiffFile, inferLanguage, parsePatch } from "./model.ts";
export {
	type Diagram,
	type DiagramKind,
	type DiagramVisualPlan,
	type DiffMeasurement,
	type DiffPlanStyles,
	type DiffPlanVisibility,
	type DiffStructure,
	type DiffVisualPlan,
	diffStructure,
	EXCERPT_HUNK_OLD_START,
	type ExcerptQuotation,
	type ExcerptSpans,
	type ExcerptVisualPlan,
	excerptLineRange,
	measureDiff,
	type PaintDiffInput,
	type PaintedDiffRow,
	type PaintedDiffSlice,
	type PaintedGutter,
	type PaintedHunkHeaderRow,
	type PaintedSplitLineRow,
	type PaintedStackLineRow,
	type PaintedVisualCell,
	type PlanDiagramInput,
	type PlanDiffInput,
	type PlanExcerptInput,
	type PlannedDiagramRow,
	type PlannedDiffRow,
	type PlannedExcerptRow,
	type PlannedGutter,
	type PlannedHunkHeaderRow,
	type PlannedRow,
	type PlannedSplitLineRow,
	type PlannedStackLineRow,
	type PlannedVisualCell,
	paintDiff,
	planDiagram,
	planDiff,
	planExcerpt,
	structureRowIdentity,
} from "./plan.ts";
export { anchorRowIndex, plannedRowIdentity } from "./ranges.ts";
export {
	canonicalizeDiffSelection,
	type DiffPresentationRow,
	type DiffSelection,
	type DiffSelectionRange,
	type DiffSelectionStop,
	diffPresentationRows,
	diffSelectionStops,
	firstSelectionRange,
	moveSplitSelectionStop,
	moveStackedSelectionStop,
	type NonEmptyArray,
	normalizeDiffSelection,
	presentationRowStop,
	rectangularSelectionBetween,
	selectionBetween,
	selectionContains,
	stackedSelectionBetween,
	stackedVisibleSelectionStops,
	switchSplitSelectionStop,
	terminalSelectionRange,
} from "./selection.ts";
export { compositeTerminalForeground } from "./syntectTheme.ts";
export { plainTerminalLine, sanitizeTerminalLine } from "./terminalText.ts";
export type {
	DecorationAnchor,
	DiffChangeContent,
	DiffContextContent,
	DiffFile,
	DiffFileInput,
	DiffHunk,
	DiffHunkContent,
	DiffLayout,
	DiffLine,
	DiffLineRange,
	DiffMetadata,
	DiffRow,
	DiffSide,
	DiffSourceLineIdentity,
	DiffStats,
	DiffStatus,
	EmphasisRange,
	RangeDecoration,
	RenderSpan,
} from "./types.ts";
